replicas: 2

stateful: false

image:
  repository: busybox
  tag: latest

command: []

loadbalanced: false

istio: true

ports:
  http: 8080

ingress:
  localonly: true
  enabled: true
  host: deangalvin.dev

serviceMonitor:
  enabled: true
  path: /metrics
  scheme: http

persistence: {}
  #  config:
  #    type: secret
  #    name: myapp-secret
  #    items:
  #      - key: server.toml
  #      - path: server.toml

env: {}
  #KEY: value

newTemplate: {}

resources: {}
