replicas: 2

image:
  repository: busybox
  tag: latest

command: []

ports:
  http: 8080

ingress:
  enabled: true
  host: deangalvin.dev

serviceMonitor:
  port: http
  path: /metrics
  scheme: http

persistence: {}
  #  config:
  #    type: secret
  #    name: myapp-secret
  #    items:
  #      - key: server.toml
  #      - path: server.toml

newTemplate: {}
