{{- if .Values.transcoding.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "unicorn-plex.fullname" . }}
  labels:
    {{- include "unicorn-plex.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "unicorn-plex.name" . }}-transcoder
  minReplicas: {{ .Values.transcoding.replicas }}
  maxReplicas: {{ .Values.transcoding.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.transcoding.hpa.CPUPercent }}
{{- end }}
