---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unicorn-plex.fullname" . }}-claimtoken
  labels:
    {{- include "unicorn-plex.labels" . | nindent 4 }}
type: Opaque
stringData:
  claimToken: {{ .Values.claimToken | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unicorn-plex.fullname" . }}-x-plex-token
  labels:
    {{- include "unicorn-plex.labels" . | nindent 4 }}
type: Opaque
stringData:
  X-Plex-Token: {{ .Values.XPlexToken | quote }}
