apiVersion: v1
kind: Service
metadata:
  name: {{ include "unicorn-plex.fullname" . }}-transcode
  labels:
    {{- include "unicorn-plex.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: transcode-port
      port: {{ .Values.service.port }}
      targetPort: transcode-port
      protocol: TCP
  selector:
    unicorn-transcoder: transcoder
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "unicorn-plex.fullname" . }}
  labels:
    {{- include "unicorn-plex.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: lb-port
      port: {{ .Values.service.port }}
      targetPort: lb-port
      protocol: TCP
    - name: plex-companion
      port: 3005
      targetPort: plex-companion
      protocol: TCP
    - name: plex-roku
      port: 8324
      targetPort: plex-roku
      protocol: TCP
    - name: dnla-server2
      port: 32469
      targetPort: dnla-server2
      protocol: TCP
  selector:
    unicorn-transcoder: loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "unicorn-plex.fullname" . }}-udp
  labels:
    {{- include "unicorn-plex.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: dnla-server
      port: 1900
      targetPort: dnla-server
      protocol: UDP
    - name: plex-discovery
      port: 5353
      targetPort: plex-discovery
      protocol: UDP
    - name: plex-gdm1
      port: 32410
      targetPort: plex-gdm1
      protocol: UDP
    - name: plex-gdm2
      port: 32412
      targetPort: plex-gdm2
      protocol: UDP
    - name: plex-gdm3
      port: 32413
      targetPort: plex-gdm3
      protocol: UDP
    - name: plex-gdm4
      port: 32414
      targetPort: plex-gdm4
      protocol: UDP
  selector:
    unicorn-transcoder: loadbalancer
