{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "unicorn-plex.serviceAccountName" . }}
  labels:
{{ include "unicorn-plex.labels" . | nindent 4 }}
{{- end -}}
